apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
  namespace: homepage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homepage
  template:
    metadata:
      labels:
        app: homepage
    spec:
      initContainers:
        - name: copy-configs
          image: busybox
          command:
            - sh
            - -c
            - cp /config-source/* /app/config/
          volumeMounts:
            - name: config-source
              mountPath: /config-source
            - name: config-dir
              mountPath: /app/config
      containers:
        - name: homepage
          image: ghcr.io/gethomepage/homepage:latest
          env:
            - name: HOMEPAGE_ALLOWED_HOSTS
              value: "dashboard.vi3t-lab.com"
            - name: HOMEPAGE_VAR_PIHOLE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: pihole-api-token
                  key: token
          ports:
            - containerPort: 3000
              name: http
          volumeMounts:
            - name: config-dir
              mountPath: /app/config
      volumes:
        - name: config-source
          configMap:
            name: homepage-config
        - name: config-dir
          emptyDir: {}
