apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pihole-api-token
  namespace: homepage
spec:
  encryptedData:
    token: AgBkNG7PlwsKKx44myGWbavhHl8sLTX8AsMpi58cKD0K6lKawvRNzAc6Mzp2MXjDh1TAv3Oh+kcB0y7ij31il0pvKImiDOQJ9vffVTw50naoqEmY/UIMfPSRxUey8xea1Tcv3NV2WwV71sUb4XqnYLmB12/Tzz338OgcfOpMLDvyKcqEouJf18YwX2H2D6njYJXCJ2a1/cBxUHrCFYmOWm+Q9CVRk1qn+5ESXik+gW29Y4YOHaeUa1iXVDHdGQGRvGZ1m9ITqsNSOxT1h/WPG/qiuF3AkWe7zz6XjufVXHdua4Xr7RGv7a2XqELKiIyjwDInUYFcaBzd3IkJkEp+3JpeA5EZzYdC2TKi+RlKatROb+BLzmBz7Oxs3tYh4ehJaUXWwBxJ9lAgSZEIbwAOxjq5J2BNSJJU9rsuODb+HvEIs77UOqRI95tCpEq9FUw1T2fSTiQyykim6IbhzfQlmQw+7h5SNnc+DyHLbpofrTA/G7JH0s5bF9fTyMuE0WlGHHc54ABexqroNm4DpB29YfomPC1ciyB2/GeGCbNVB92Y2msXGV+lcI9MMIAc4H5P1WgBVlRaH8Px1r/ejgG/Y0hpHQRne26YNRJBJbOSTQgduDl/DfMZbu7+uDY65DqGKEdfW5MwkA9V5s+EXVyzXZlXbfNAmaJoHQoFdXcqh+mc0+5Y6U2OQvloz97XycVgOYjnEEtX1MDsG2jMkkYgQ3B9FkNMN7+O3wJ2G4CosxS+HhZuqFKp8LmnkQ8FPjAY9aULrGz7MSkl5Du90vUM3lMf
  template:
    metadata:
      creationTimestamp: null
      name: pihole-api-token
      namespace: homepage
