apiVersion: v1
kind: Namespace
metadata:
  name: homepage
---
# -------------------
# CONFIGURATION
# -------------------
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  namespace: homepage
data:
  # File 1: General Settings
  settings.yaml: |
    title: Tran's Home Lab
    background: https://images.unsplash.com/photo-1550684848-fac1c5b4e853?q=80&w=2070&auto=format&fit=crop
    cardBlur: sm
    theme: dark
    color: slate

  # File 2: The Links (Services)
  services.yaml: |
    - Management:
        - Uptime Kuma:
            icon: uptime-kuma.png
            href: https://uptime.192.168.1.4.nip.io
            description: Network Monitor
        - ArgoCD:
            icon: argocd.png
            href: https://argocd.192.168.1.4.nip.io
            description: GitOps Controller

  # File 3: Widgets (System Info)
  widgets.yaml: |
    - resources:
        cpu: true
        memory: true
        disk: true

  # File 4: Bookmarks (Optional)
  bookmarks.yaml: |
    - Developer:
        - GitHub:
            - abbr: GH
              href: https://github.com/

---
# -------------------
# THE APPLICATION
# -------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
  namespace: homepage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homepage
  template:
    metadata:
      labels:
        app: homepage
    spec:
      containers:
      - name: homepage
        image: ghcr.io/gethomepage/homepage:latest
        ports:
        - containerPort: 3000

        # FIX 1: Tell the app to allow your specific URL (or all URLs with "*")
        env:
        - name HOMEPAGE_ALLOWED_HOSTS
          value: "*"

        volumeMounts:
        - name: config
          mountPath: /app/config  # We inject the files here
        # FIX 2: Give the app a witable folder for its logs
        - name: logs
          mountPath: /app/config/logs

      volumes:
      - name: config
        configMap:
          name: homepage-config   # From the ConfigMap above
        # FIX 2 (Continued): Create the temporary empty volume for logs
      - name: logs
        emptyDir: {}

---
# -------------------
# NETWORKING
# -------------------
apiVersion: v1
kind: Service
metadata:
  name: homepage-service
  namespace: homepage
spec:
  selector:
    app: homepage
  ports:
  - port: 80
    targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homepage-ingress
  namespace: homepage
  annotations:
    cert-manager.io/cluster-issuer: selfsigned-issuer # Use the robot for SSL
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - home.192.168.1.4.nip.io
    secretName: homepage-tls-secret
  rules:
  - host: home.192.168.1.4.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: homepage-service
            port:
              number: 80