apiVersion: v1
kind: Namespace
metadata:
  name: homepage
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  namespace: homepage
data:
  settings.yaml: |
    title: Home Lab
    background: "#0f172a"
    cardBlur: sm
    theme: dark
    color: slate
    layout:
      Management:
        style: row
        columns: 2
  services.yaml: |
    - Management:
        - Uptime Kuma:
            icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/uptime-kuma.png
            href: https://uptime.192.168.1.4.nip.io
            description: Network Monitor
        - ArgoCD:
            # FIX: Official CNCF Artwork Repository (The Orange Octopus)
            icon: https://raw.githubusercontent.com/cncf/artwork/master/projects/argo/icon/color/argo-icon-color.png
            href: https://argocd.192.168.1.4.nip.io
            description: GitOps Controller
    - Network:
        - Pi-hole:
            icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/pihole.png
            href: http://192.168.1.68/admin/
            description: Ad Blocker
            widget:
             type: pihole
             url: http://192.168.1.68/
             key: "b4QiRTw+T45kvG6KDnOUpFYK2lJzujgN3WQ54ZLYcQ0="
  widgets.yaml: |
    - greeting:
        text_size: xl
        text: "Welcome Home, Tran."
  bookmarks.yaml: |
    - Developer:
        - GitHub:
            - abbr: GH
              href: https://github.com/
  kubernetes.yaml: |
    mode: cluster
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
  namespace: homepage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homepage
  template:
    metadata:
      labels:
        app: homepage
    spec:
      initContainers:
      - name: copy-config
        image: busybox
        command: ['sh', '-c', 'cp /config-source/* /app/config/']
        volumeMounts:
        - name: config-source
          mountPath: /config-source
        - name: config
          mountPath: /app/config
      containers:
      - name: homepage
        image: ghcr.io/gethomepage/homepage:latest
        ports:
        - containerPort: 3000
        env:
        - name: HOMEPAGE_ALLOWED_HOSTS
          value: "*"
        volumeMounts:
        - name: config
          mountPath: /app/config
      volumes:
      - name: config-source
        configMap:
          name: homepage-config
      - name: config
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: homepage-service
  namespace: homepage
spec:
  selector:
    app: homepage
  ports:
  - port: 80
    targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homepage-ingress
  namespace: homepage
  annotations:
    cert-manager.io/cluster-issuer: selfsigned-issuer
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - home.192.168.1.4.nip.io
    secretName: homepage-tls-secret
  rules:
  - host: home.192.168.1.4.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: homepage-service
            port:
              number: 80