apiVersion: v1
kind: Namespace
metadata:
  name: homepage
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  namespace: homepage
data:
  settings.yaml: |
    title: Home Lab
    background: https://images.unsplash.com/photo-1550684848-fac1c5b4e853?q=80&w=2070&auto=format&fit=crop
    cardBlur: sm
    theme: dark
    color: slate
  services.yaml: |
    - Management:
        - Uptime Kuma:
            icon: uptime-kuma.png
            href: https://uptime.192.168.1.4.nip.io
            description: Network Monitor
        - ArgoCD:
            icon: argocd.png
            href: https://argocd.192.168.1.4.nip.io
            description: GitOps Controller
  widgets.yaml: |
    - resources:
        cpu: true
        memory: true
        disk: true
  bookmarks.yaml: |
    - Developer:
        - GitHub:
            - abbr: GH
              href: https://github.com/
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
  namespace: homepage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homepage
  template:
    metadata:
      labels:
        app: homepage
    spec:
      containers:
      - name: homepage
        image: ghcr.io/gethomepage/homepage:latest
        ports:
        - containerPort: 3000
        env:
        - name: HOMEPAGE_ALLOWED_HOSTS
          value: "*"
        volumeMounts:
        - name: config
          mountPath: /app/config
        - name: logs
          mountPath: /app/config/logs
      volumes:
      - name: config
        configMap:
          name: homepage-config
      - name: logs
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: homepage-service
  namespace: homepage
spec:
  selector:
    app: homepage
  ports:
  - port: 80
    targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homepage-ingress
  namespace: homepage
  annotations:
    cert-manager.io/cluster-issuer: selfsigned-issuer
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - home.192.168.1.4.nip.io
    secretName: homepage-tls-secret
  rules:
  - host: home.192.168.1.4.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: homepage-service
            port:
              number: 80