apiVersion: v1
kind: Namespace
metadata:
  name: gaming
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-data
  namespace: gaming
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft
  namespace: gaming
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      # 1. NEW: Init Container to Force Download the File
      initContainers:
      - name: download-server
        image: busybox
        command: ["sh", "-c"]
        args:
          - |
            echo "Downloading PaperMC manually..."
            # Force download ignoring SSL (The --no-check-certificate flag is the magic)
            wget --no-check-certificate -O /data/server.jar https://api.papermc.io/v2/projects/paper/versions/1.20.4/builds/496/downloads/paper-1.20.4-496.jar
            chmod 777 /data/server.jar
        volumeMounts:
        - name: data
          mountPath: /data
      containers:
      - name: minecraft
        image: itzg/minecraft-server:java17
        imagePullPolicy: Always
        ports:
        - containerPort: 25565
          name: game
        env:
        - name: EULA
          value: "TRUE"
        # 2. CHANGE: Tell it we are providing our own file
        - name: TYPE
          value: "CUSTOM"
        - name: CUSTOM_SERVER
          value: "/data/server.jar"
        - name: MEMORY
          value: "2G"
        - name: MOTD
          value: "K8s Cluster Survival"
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
          limits:
            memory: "3Gi"
            cpu: "3000m"
        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: minecraft-data
---
apiVersion: v1
kind: Service
metadata:
  name: minecraft-service
  namespace: gaming
spec:
  selector:
    app: minecraft
  type: LoadBalancer
  ports:
  - port: 25565
    targetPort: 25565
    protocol: TCP