apiVersion: v1
kind: Namespace
metadata:
  name: gaming
---
# 1. STORAGE: Keep your world safe if the pod restarts
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-data
  namespace: gaming
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
# 2. THE SERVER: The actual game logic
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft
  namespace: gaming
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      containers:
      - name: minecraft
        image: itzg/minecraft-server:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 25565
          name: game
        env:
        - name: EULA
          value: "TRUE"
        - name: TYPE
          value: "PAPER"  # "Paper" is optimized for low-resource hardware like Pis
        - name: VERSION
          value: "1.20.4" # Pinning version is safer than "LATEST"
        - name: MEMORY
          value: "2G"     # Leaves 2GB for the OS and K3s
        - name: MOTD
          value: "K8s Cluster Survival"
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"  # Request 1 full core
          limits:
            memory: "3Gi" # Hard cap so it doesn't crash the Pi
            cpu: "3000m"
        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: minecraft-data
---
# 3. NETWORK: Open the port to your LAN
apiVersion: v1
kind: Service
metadata:
  name: minecraft-service
  namespace: gaming
spec:
  selector:
    app: minecraft
  type: LoadBalancer # On K3s, this will expose it on the Node's IP
  ports:
  - port: 25565
    targetPort: 25565
    protocol: TCP