apiVersion: v1
kind: Namespace
metadata:
  name: gaming
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-data
  namespace: gaming
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft
  namespace: gaming
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      # 1. NEW: Force Google DNS to bypass local router issues
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 8.8.8.8
          - 8.8.4.4

      # 2. NEW: Alpine Downloader with Curl
      initContainers:
      - name: download-server
        image: alpine:latest
        command: ["sh", "-c"]
        args:
          - |
            apk add --no-cache curl
            echo "Resolving papermc.io..."
            # Debug: show us what IP it finds
            nslookup api.papermc.io
            
            echo "Downloading PaperMC..."
            # Use the latest 1.20.4 build (496)
            curl -L -k -o /data/server.jar https://api.papermc.io/v2/projects/paper/versions/1.20.4/builds/496/downloads/paper-1.20.4-496.jar
            
            chmod 777 /data/server.jar
            echo "Download complete."
        volumeMounts:
        - name: data
          mountPath: /data

      containers:
      - name: minecraft
        image: itzg/minecraft-server:java17
        imagePullPolicy: Always
        ports:
        - containerPort: 25565
          name: game
        env:
        - name: EULA
          value: "TRUE"
        - name: TYPE
          value: "CUSTOM"
        - name: CUSTOM_SERVER
          value: "/data/server.jar"
        - name: MEMORY
          value: "2G"
        - name: MOTD
          value: "K8s Cluster Survival"
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
          limits:
            memory: "3Gi"
            cpu: "3000m"
        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: minecraft-data
---
apiVersion: v1
kind: Service
metadata:
  name: minecraft-service
  namespace: gaming
spec:
  selector:
    app: minecraft
  type: LoadBalancer
  ports:
  - port: 25565
    targetPort: 25565
    protocol: TCP