apiVersion: v1
kind: Namespace
metadata:
  name: gaming
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-data
  namespace: gaming
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft
  namespace: gaming
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      # 1. NETWORK: Keep the Google DNS fix so it can download files
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 8.8.8.8
          - 8.8.4.4
      
      # 2. CLEANUP: No more "initContainer" manual download.
      
      containers:
      - name: minecraft
        # 3. JAVA: Ensure we use Java 21 for modern versions
        image: itzg/minecraft-server:java21
        imagePullPolicy: Always
        ports:
        - containerPort: 25565
          name: game
        env:
        - name: EULA
          value: "TRUE"
        # 4. VERSION: Force it to match your client exactly
        - name: VERSION
          value: "1.21.11"
        # 5. TYPE: Switch back to PAPER (It's faster on Pis). 
        # If Paper 1.21.11 doesn't exist yet, change this to "VANILLA"
        - name: TYPE
          value: "PAPER"
        - name: ENABLE_QUERY
          value: "TRUE"
        - name: MEMORY
          value: "2G"
        - name: MOTD
          value: "Tran's Cluster Fortress"
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
          limits:
            memory: "3Gi"
            cpu: "3000m"
        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: minecraft-data
---
apiVersion: v1
kind: Service
metadata:
  name: minecraft-service
  namespace: gaming
spec:
  selector:
    app: minecraft
  type: LoadBalancer
  ports:
  - port: 25565
    targetPort: 25565
    protocol: TCP