apiVersion: v1
kind: Namespace
metadata:
  name: gaming
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-data
  namespace: gaming
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft
  namespace: gaming
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      # Network Fix for Downloads
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 8.8.8.8
          - 8.8.4.4
      containers:
      - name: minecraft
        image: itzg/minecraft-server:java21
        imagePullPolicy: Always
        ports:
        # 1. TCP for Playing
        - containerPort: 25565
          name: game
          protocol: TCP
        # 2. UDP for Stats (Homepage needs this!)
        - containerPort: 25565
          name: query
          protocol: UDP
        env:
        - name: EULA
          value: "TRUE"
        # 3. VERSION MATCH: Your screenshot says 1.21.1, so let's match it perfectly.
        - name: VERSION
          value: "1.21.1"
        - name: TYPE
          value: "PAPER"
        - name: ENABLE_QUERY
          value: "TRUE"
        - name: MEMORY
          value: "2G"
        - name: MOTD
          value: "Tran's Cluster Fortress"
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
          limits:
            memory: "3Gi"
            cpu: "3000m"
        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: minecraft-data
---
apiVersion: v1
kind: Service
metadata:
  name: minecraft-service
  namespace: gaming
spec:
  selector:
    app: minecraft
  type: LoadBalancer
  ports:
  # 4. EXPOSE BOTH PORTS IN THE SERVICE
  - port: 25565
    targetPort: 25565
    protocol: TCP
    name: game
  - port: 25565
    targetPort: 25565
    protocol: UDP
    name: query