apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-config
  namespace: networking
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-dnsmasq
  namespace: networking
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole
  namespace: networking
  labels:
    app: pihole
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: pihole
  template:
    metadata:
      labels:
        app: pihole
    spec:
      containers:
      - name: pihole
        image: pihole/pihole:latest
        imagePullPolicy: Always
        env:
        - name: TZ
          value: "America/Chicago"
        - name: WEBPASSWORD
          valueFrom:
            secretKeyRef:
              name: pihole-secret
              key: WEBPASSWORD
        - name: DNS1
          value: "1.1.1.1"
        - name: DNS2
          value: "8.8.8.8"
        ports:
        - containerPort: 53
          name: dns-tcp
          protocol: TCP
        - containerPort: 53
          name: dns-udp
          protocol: UDP
        - containerPort: 80
          name: web
          protocol: TCP
        volumeMounts:
        - name: config
          mountPath: /etc/pihole
        - name: dnsmasq
          mountPath: /etc/dnsmasq.d
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "100m"
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: pihole-config
      - name: dnsmasq
        persistentVolumeClaim:
          claimName: pihole-dnsmasq
---
apiVersion: v1
kind: Service
metadata:
  name: pihole-service
  namespace: networking
  annotations:
    metallb.universe.tf/allow-shared-ip: "pihole-svc"
spec:
  selector:
    app: pihole
  type: LoadBalancer
  # Pick your IP here
  loadBalancerIP: 192.168.1.23
  ports:
    - port: 53
      targetPort: 53
      protocol: TCP
      name: dns-tcp
    - port: 53
      targetPort: 53
      protocol: UDP
      name: dns-udp
    - port: 80
      targetPort: 80
      protocol: TCP
      name: web
