apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCKzue50SCFNQZW9T57vOEtEqtiYOof5Y/fmNR6I+++qQbXNG6wXGpune1/xiVXOysMkfHOR43Gbmgf0fe2Yj5vplx6C7ds7iBP6Haz95MSUYbvpQlpXUJ9hu85/zHOwpE4UV2/BSoEdD7eDA/CAv1oRrDLRD/mIK0Gopx5zg0XyqrHx6pHVODrg7GPyFub1/bEVaiCLScU6vg6tENCywD0TyZ/YwqMPLIPPgzMWZYS+U4VR4AjhIXpqP2H0O31RJF0DFz0hi+pdqLJRNshU9dqC6ALfwSLoKHu2KnxPF/DPM44e85wCNy974xPs0+Jv6+ziI95810A2T+f/MzcjvPkOvQrWcNe2Mmce8LYr9EJBsoIiX5AraE6SnChTmTXagiuxFQCMZLHzcgZrLcmP7DGUPTVnZYsVwFtIQkupaPIfgcD5AdMC5ZjgRO2nknaG21XbIf+j3jxiRM+PRKDCeMtQCrudH458HJRhriGWXM2ZIa/22tyrI+41cidZ3aUhUcKr9KAPSWNwpT+aBNbH7GzW+oNramVSQQaHEjjpMKiCutETOAycaBjuJzGtffnYQobj4dNKjCkxaoQCZ8qpNhvLsXYQxU91QQ6CoFlbfw2uCXDtcQUBxoOOIXyeXh8mHfqyN2aJ8jgV5BlkuVZ8vcHKuqboRVzeSVgG5JWm+7lMYMUcq8KeP/iJd02+vmbErylVguUyyrl+6o+
    admin-user: AgCpWFjC8cm8SeOkyhVkBg/jSWlx8ydS/YTftWqI636U7UV0bO6q8A896BOmOrgt4bqFJr+M4UKgMx7t+WbZcC4IcJffMSGM2C5thDKrQj4GF5/k8NoF6pjOzVPd4MVN3tBnVZGjW70NHH+bPLr+dgugx0ds3rxVYSoryHZKR5xIR0I3UmSCXT/2EE+f318HOzaTC4fO042Rx4Zc5WpOafGuWiQgYO3VwXf8kRU2ww+ct24iJz6ExHtRvGl19zzIMCEV3vCHNkDrHajPwX3etLKDuNPuilS+T7ZXNItpD/qv6EMMW1FYHpHlWduq8iRI1EVbDqVXmEL7zKGmYD3ZCPQYA+3DOCy1A41vDhSJbu2p6jJDbd6z6vydPmmC5VFGjqFADuebgUEAiRSpFbCFXUvHTjlfRACUsXn+90N79WuF8W1Zz7dubRac5s6JaEfUovZ69+4ZG1PispIOR/jxkwbrJbI4sNjk0A6nAp8Kv/05S+PcEqJxyOyjXEXtDZ2nC2bqGAc+2LYQYPNUvyZ9ehXI8NJGK6WA1Uim8uDErP7fnalhahuLQMWfVYGDyZQkTp4FcUzZIMOVrZ0zRy+VouGUCJF6h8m9y57vqg79zP4cDIqKIhG+ysDfNvGTCKduYXXU6AprryF9IKSBBc7s3NgeU7zGxHyFogk7wsr3fUfxj2jpEFFV/U1YCuxgyAJgV8zpPxb3mw==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin-secret
      namespace: monitoring
