apiVersion: v1
kind: Service
metadata:
  name: openvpn-as
  namespace: openvpn
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.30.192
spec:
  type: LoadBalancer
  selector:
    app: openvpn-as
  ports:
    - name: vpn-udp
      port: 1194
      protocol: UDP
      targetPort: 1194
    - name: web-ui
      port: 943
      protocol: TCP
      targetPort: 943
    - name: vpn-tcp
      port: 443
      protocol: TCP
      targetPort: 443
