apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-ddns-token
  namespace: cloudflare-ddns
spec:
  encryptedData:
    CF_API_TOKEN: AgBdp5DtTmfV64GmORzshyknsdxf6/p1MUw6B9CXiRXLZC1k495MnQWqmsVgSC2MQN5DlnCoXIr9GJuPuwHeNzI1owUz7R/N06y9BL9kfAe//swvmxzQXwUdMU0EsUZq6mawhWiDplWlPD/xfU3vj2C5MKStAH4If9CuiIPz3/yvFTSgi1dmmDa0oiwcPfwazJ4fDK/DyUFwr5IJqpO8Appzwr6IADtVry+x2kQfWp4R6tjdyRiHVcZB/AhTl/c7rAbe7YjulsW7GMKvJ4R8DHTOYNgZWchk9KE28KYDQL04a+C7Z+x+sA4XX5keYh54Uu4NvjHlqg6SeBnsCx66rWiigR7Q/9s3+OukG+8F0l0hBYiUeWSK81L+4uXfxj5ko62YqhjckmCK+wTOeIPuWzdTXszmqvJyqgtBnn6dfhjdOv8NCIv1bUX5pmsOXWXeBdXh7x0DfNomwi6LLIfhj2wBxZJ8Rm7jA7WV5hde3lychlybRC1am9AiFU2PUw/1eQmF/eUYV9wh97kUCOJS8aUsCjDz45BH37Q9IBP10Hs1saJuEKrzIBTZJ1yTPJklRw0JjkObJIXo2guFO0MS4y76BAwHaHL0+yq242zmHAApB2ohfm46lz4IpTGJjPziBrKlT4FF9MMI3JbpUR88mpua2CbV+QGYi+PMYXmQeR+4xrG0zsdK1Yi8X1Kc7zk9EyRKZUya1wEERa0apYNIzEhChzrjSpm64Y+1xcTr2Ubb78WNlXQzbJFb
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-ddns-token
      namespace: cloudflare-ddns
