apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-ddns-token
  namespace: cloudflare-ddns
spec:
  encryptedData:
    CF_API_TOKEN: AgAOnjA9RqPlU2QsCaoxon/F7lZ1GVZE+vNwmqKLfuDZZBhxZIFiSMKH9KZAdtLQ0HsDc0ElqaTev9vyavlWSSjtcP4Ano8w+DLic/A2aex1cwJ59Tv5XZR/RZEVuFoS7bhz9yXjDWYalY7CpNligCmvZLLIs6HPPh79NwpfYZWcXgbTMhQGcwn1uiAqZBpmgQQIQfgpf/F56XIRotE5KODmdaYxO0xAZ9Fjq/fDAgh5yDvcWPynqy1G+uBdru+UReXiHKBywUzT9urtklS5/IR0m+qrgojOpu2D5rg7SR3S5eY5L9zKk8Q+dtBzjdpsGLH11suRy7wXxty/c1CaqKMEP9jeBmAX+2jmPJqaoxnb6QtvKy5/6UgAOx/yvegbzPC/4oMY2bJNQCKDow3c/8l5V1kTf2gApAbDqebZQ1jj1sVfHBFSnLZ3Q8qIu4c5sXN+QKB6SCcSzYUbAmPzyIg13m0w0b7Zud7BzFfWKQ1Kx4Dv5S6/pXq/OAP8oeOTeKgLMEbcOAIUdqnNm8NEjkPXagseSVXk8ixoNkcx9VGpSjzRtadaSiMm/y0DEV1JHZxkE+wihddMEWjs4BGWbnpgX8ZbTp8cKxpzGhvaZZhVumBXiS/S0LvHqfFhEetG16R8oHzKgZNEhWlvHhnbzG17K93jjP0cdPN9glLnvxmg/N8/kwfBPFS2jj4Yo8KRkx6Iv8/82Xsk7vzmrJZPPZEdeUO3n05ALoC2OfEw4ATXMcAiRxCGxbKV
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-ddns-token
      namespace: cloudflare-ddns
