apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBYzQjXlvwYOehjZs5KCPOsuU4Ameu7bW2roqduLecISKsU8jPIk/WuiuVC1b+l+wz0wNw8/k3sRT6hib6gsJtBfS4IH39TZL5xzNaCftxO3X44CjrWcwt7tKW4QSvrkK9U8rHK5B3ZgfeKEzid/NKWI8ON7uTK4YMFaZ/JURSvyherCj1BSSoVyN+1cq4ad5zznxP52YCA4PxZHV0b92AMSoVgfwkBFe2h0Wn3s9yhNSMi5N0yWDp0DmAASUMlJoQd35koreuWesgI7MS0Zou1xsbPBl58QhhM00jP9h0cAjCvvqt2XDirq39f6/HtyzmFjwB4Bh190fbEcfg0hK+PlBTQTfPONeRga/P7htMogGjOjkpgyr0TfQL9NOTtZoKwP55St8egoM0tXMI4JNQR9fvb2T0gyS6NbXKHNXqr436AGGJ9FBdQsW6QKrHGG4aVEjyzzOb//6l4tjRFILOK6Vp8oq1VQFKicl8hl3/l01atoOD+/ODUUBFMGquUwiQtOV17ikCylezVId8RqGjFBH/Jl4dGvWXLdJPxPkfnc6x8nBLV06M6sHhqiS+CZC+H6f0L9vyt7zNAG2YmJjlFKmA7aAQv5R36SV1wALDPI0iFPtGsptWpI0tpffWTyek8k8tmXhGpMW0eEG5JXNtqCDUxtp0iUkNfNL5rJJlrdt2K+GMC/Mb+nzFsQabdW7SZH9Alwx6rXLkP9hIamEII6C10YTTqKB7faVS46zO2/vZz5TF95FIK
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager