apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Added query strings to tell Kustomize these are raw files, not Git repos
  - https://github.com/external-secrets/external-secrets/releases/download/v0.9.13/external-secrets.yaml?timeout=90s
  - https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.26.1/sealed-install.yaml?timeout=90s
  - metallb-config.yaml
  - cert-manager/
  - argocd-ingress.yaml