---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pihole-secret
  namespace: pihole
spec:
  encryptedData:
    password: AgBQ+lMVaRAZe6AoQ6+sDvAjFpXysyoYgMg5cgYQ/Ww6wlScqWx1F2W+vbpSj6EV8hhZSPRswOIAoPhnSd+31rSFMoz4Pi8kyn0+3Jt82Cr+d1VBnnq4aEckAQSsAylxaq4iT2EWJVSufLVdfbGlaIFMAN2L53/bygO3pimC1AZa7oxrrNoxo2bEQ0cTrXEOW3MVeH3k65lOOpKdMIXzra7e/CwUY6yZ1c9vcAGGMLmZ0Uu8jPikdrnuXvmWLU7yhcua/OnzNHL7gFUvD7EkX5hhyvfllzhfXT23caHIxZwyq7zmKaceoN4D2ZVH+4CPlDI+LEPVXB8J+qeBwkbM2E8iOY/2fF/hhElohOxJFruMCt2FYyESakiN8MYmVMRObMSuUU3kDWU04hPPI6kCHYjiGUx8IW8owatRdv0dlomAJlc/TRHMzcRzs/epnxRk8Zq7H3qOgpR+xrukyIhLigTPEhWmbYQL2l0KH88KhiGmaRo2G05oYYshdpXVMhEYi9v+3UdihVp3KHuMowkjW68Bafa9vhp6u302wj/5nBb8Yq+TtJeOFefItp9zXZvwh6z9+L0jUXUYoUJpL9niJqcGcdkr6EceI1Czz8k8uXSTPtt/jRbgrY+Ft2anCISGdqk1m7/E6t+JBZIeuD4xnOekoUHScSLLcsH7AamtzjTZVL6D1fT2Kba+jehSgOXLU42EoXeudKT8Zobh
  template:
    metadata:
      creationTimestamp: null
      name: pihole-secret
      namespace: pihole
