apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: wg-easy-secret
  namespace: wireguard
spec:
  encryptedData:
    WG_PASSWORD: AgA94OnRIwEbvqGKh0Y+a1r/+WJ813ViO2M78RrlzEHl1EfRDd9gpDuOvuQCSYDBOtONXwoDxM4aHopa2WUvVaLR9M3fElNmGa3Pj+oI2RnHYUpytiBojznxTVp/wmbz78Gv1AID3lUHs/IOOAKTvVWtnwPECcPT40fr6cpS2L6Gy34GZX3CtFpMftJmK5ig/yLnCW3uiW2lSKSJTp+bsVrh1fRKUJnp/txw7DPNCYbFROmneH0sGyj1Vcp73T3Gxai1MwqIG6Y0HWOtK/FoYVBDmbO0hongXaaf7i00ux3LF75a/Fj7rORgq6N/VcYmF1YX2D3MgknZoBQJPY4m2atox6KsnPmFjPzbslmFkhLfV8cN0sjswQdUv3QDz0o3CRgR1JgvSp6vcw29hfm3uosqe4ppWllUhiePF8zgZpbOPcRZbPQbqpg29afrW9AcdJlTNqSq1ljIixGu+SIG26JeCrJ4cLgJ9RWzEif4Qen0Ee2Dt05TMHeDTOiSRC1cZim4l/+VS5tLwJmZCedr+2rYa82peJpNORdjtqsiM3JWRTqsfNDR16hmrzwiJjUelrsKElnGcViIk9h2/logu8LJqNdQPZ8MUDTVEwBm8pyfmNzca/TAwNtGJOw22zc6dgMhlKLVdDgmYRX5f7qOdWmeDcqHQbwjbdpf0NmPWSyvnbih0CM9Ui5cVZoxyYHyDpxGB15DMxdGN/b+bmvthv3zo7Mpruv4YcmW9zuexgRkCRho1YfHTX5AkUJ4q193ytgVrnrB1kwJeCNXSO8=
  template:
    metadata:
      creationTimestamp: null
      name: wg-easy-secret
      namespace: wireguard
