apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: wg-easy-secret
  namespace: wireguard
spec:
  encryptedData:
    WG_PASSWORD: AgB5vw9yG5pU1RsGmB5yurLLkFtLD6MmhRnyoPAzzL4zOizhZrtuf7cIKOACenyVnK9+QrBI34L0/36KCDkOS4vKVn3wxg3+ojEEJ3M+3uSjul+AXUN/9Evd2jATh+1cJjsgp12De3kpW3o92lisbtu1VBvQTw0oTU1IIT2jGDzc59MWWvdPuYXZRtI7Zm/wasKQxkYLSQyVSCBtqBVN6B1QriZTgp47iCxqz69BCEN0eUEcjrt5+zMUyFkYuKZ5v8hNPqWV80KC9TjNwNEp8Q5lHXkuR7gf6sYbDdicPeYctRskHFB0Ran7OmMUQTVxil1R7Ime0GgXvXZLcaTlAKWxQq1UOVAXPlZdU19i2L2TK9eAkm6INBBWmEIEkJUkwAe73qzBVundUQIpa0RhlzGHT90K7QhWpYYoWdudjfB6xmWOstu3ptc2JaiNrJBTMH8SfzhNaiVMMeX+Qi12jwgyC9U6zgshT4LbNwZWv28OoUVu/Ps+lU1qzpODQetqSPx6UBTZZKXCenEcKThL7JGgb4W4mbDMElZiC3MF5sdfJGx6rxOWgx2+u/OuXfL9PYW9LnZBvxoJ608odqdwgjd5d6/j5tHtqetoZ6jkFcrzfWs4Hv8iPPub+Dw59jhv/CndH2KFEra/PUjoGrIcIF4xhCE655hds9WSTatIbDnKhbCHH8/6MX/4jAK2Vn4L6YCPNj1/V4hJZqK2
  template:
    metadata:
      creationTimestamp: null
      name: wg-easy-secret
      namespace: wireguard
