apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: glances
  namespace: glances
spec:
  selector:
    matchLabels:
      app: glances
  template:
    metadata:
      labels:
        app: glances
    spec:
      hostNetwork: true
      hostPID: true
      containers:
        - name: glances
          image: nicolargo/glances:latest-full
          env:
            - name: GLANCES_OPT
              value: "-w"
          ports:
            - containerPort: 61208
              name: glances
          securityContext:
            privileged: true
          volumeMounts:
            - name: host-proc
              mountPath: /proc
              readOnly: true
            - name: host-sys
              mountPath: /sys
              readOnly: true
      volumes:
        - name: host-proc
          hostPath:
            path: /proc
        - name: host-sys
          hostPath:
            path: /sys
