apiVersion: v1
kind: Service
metadata:
  name: glances
  namespace: glances
spec:
  clusterIP: None
  selector:
    app: glances
  ports:
    - name: glances
      port: 61208
      targetPort: 61208
      protocol: TCP
