apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft
  namespace: minecraft
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      containers:
        - name: minecraft
          image: itzg/minecraft-server:latest
          env:
            - name: EULA
              value: "TRUE"
            - name: TYPE
              value: "VANILLA"
            - name: VERSION
              value: "LATEST"
            - name: RCON_ENABLED
              value: "true"
            - name: RCON_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: minecraft-rcon
                  key: rcon-password
            - name: ENABLE_QUERY
              value: "true"
          ports:
            - containerPort: 25565
              name: minecraft
            - containerPort: 25575
              name: rcon
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: minecraft-data
