apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minecraft-rcon
  namespace: minecraft
spec:
  encryptedData:
    rcon-password: AgC1iSAptHvg+mzcjwX9SMHxrvjeXatPoe4dV7gdMeoumw1SyTxd45fvPMZnDiohvy3juCBCo6T7H2jTPq0pPW5/apVH0qsznLFLiSUm+A0ZpxirkvEBoUqnaL3AylXFT0FiWXeTqo3enKImrhjRnSRBU9WgjWCOaR0feJNKNk/+tT+fottzyv0NtzaGahg3ZEjgAj2onRdLgnFVIcMVV+6hwl51ZOOah8TLhmtNf7yUCaF/eV8qAJN4J8JNOeSaRK+sxstrIj90n8Lma/a3bXxTlvBwIG5p7rBdhIvll/1m4UjbmLR635ZFs/NM83cqjeyc4kJbPnJmJa0h3LELuQ/xL/jkZWbu+1TIVC+kzTgP6O5IARV7HmPsVeKyZYkn/QQ8mrwA/2izA7NVbelQzurqJ55gNpnmWIXNNM4SKwhRifMvW3/wYFAwNSAL9H1gJDnsQSOXBansFbuITLYMhgugo50JdeZur1xfLvBF/QX8HIezzs6alI0/NEoVWa5LFKJLHS2L2teaFVbaoIWMTSTCPNwGeH2sh26lsc2Wa9O7reEZS3TaBQA4ox25F9bvoIr+PqUJnjHbnd1PbWykbyLFUeRdxkclnDVPEpdTR4SCXrtCkuXT33U0jhACi42Uc2wcdPUk3/fqznn+XujCX6Y0tdInZyDmbLGdFFgl1ckajIVqB0yFKElweR1K3uGeb+P21b/Jqdcsyg2g
  template:
    metadata:
      creationTimestamp: null
      name: minecraft-rcon
      namespace: minecraft
